### ISSUE TITLE
rails g graphql_auth:install fails 

### ISSUE THREAD

**Issue by dodecagonfd** [o2web/graphql-auth#27]
Hi, 
I am trying to install graphql-auth with the following:

rails (6.0.3.2)
devise (4.7.2)
graphql (1.11.3)
jwt (1.5.6)

When I run rails g graphql_auth:install, I face the following error:
#---
_[WARNING] Could not load generator "generators/graphql_auth/install_generator". Error: undefined method `sign_in_mutation' for nil:NilClass.
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/graphql-auth-0.2.2/app/graphql/types/graphql_auth.rb:6:in `<module:GraphqlAuth>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/graphql-auth-0.2.2/app/graphql/types/graphql_auth.rb:3:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:27:in `require'
....
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
...
Could not find generator 'graphql_auth:install'. Maybe you meant "graphql:install"?
Run `rails generate --help` for more options._
---#

I tried debugging with few monkey-patchings at app\graphql\types\graphql_auth.rb  but got lost.
Can you please help?

**Comment by davidrlarochelle** [comment]
+1

Same issue here!

**Comment by davidpatters0n** [comment]
Got the same issue  here too.
